config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'logs#index'

  resources :logs, only: %i[index show]

  resources :conditions do
    collection do
      get 'search'
    end
  end

  resources :products do
    resources :molds, only: %i[new create show destroy]
  end

  resources :machines
end

app/models/condition.rb
# frozen_string_literal: true

# Condition class
class Condition < ApplicationRecord
  validates :machine_id, presence: true, uniqueness: { scope: :mold_id }
  validates :mold_id, presence: true
  validates :lis, presence: true
  validates :lis_u, presence: true
  validates :lis_l, presence: true
  validates :his, presence: true
  validates :his_u, presence: true
  validates :his_l, presence: true
  validates :sup, presence: true
  validates :sup_u, presence: true
  validates :sup_l, presence: true
  validates :cp, presence: true
  validates :cp_u, presence: true
  validates :cp_l, presence: true
  validates :bt, presence: true
  validates :bt_u, presence: true
  validates :bt_l, presence: true
  validates :ssp, presence: true
  validates :ssp_u, presence: true
  validates :ssp_l, presence: true
  validates :dev, presence: true
  validates :dev_u, presence: true
  validates :dev_l, presence: true
  validates :fmf, presence: true
  validates :fmf_u, presence: true
  validates :fmf_l, presence: true
  validates :mmf, presence: true
  validates :mmf_u, presence: true
  validates :mmf_l, presence: true

  belongs_to :machine
  belongs_to :mold
end

app/controllers/conditions_controller.rb
# frozen_string_literal: true

# Condiitons controller class
class ConditionsController < ApplicationController
  add_breadcrumb '条件表一覧', :conditions_path

  def index; end

  def search
    machine_ids = Machine.where('name LIKE(?)', "%#{params[:machine]}%").ids
    product_ids = Product.where('name LIKE(?)', "%#{params[:product]}%").ids
    mold_ids = Mold.where('product_id': product_ids).ids
    @conditions = Condition.where('machine_id': machine_ids, 'mold_id': mold_ids)
    respond_to do |format|
      format.json
    end
  end

  def new
    @condition = Condition.new
    @product_mold_lists = {}
    Mold.all.each do |mold|
      @product_mold_lists.store("#{Product.find(mold.product_id).name} #{mold.number}次型", mold.id)
    end
    add_breadcrumb '新規登録'
  end

  def create
    Condition.create(condition_params)
    redirect_to conditions_path, notice: '新しい条件表が登録されました'
  end

  def show
    @condition = Condition.find(params[:id])
    add_breadcrumb "#{@condition.machine.name}号機 #{@condition.mold.product.name} #{@condition.mold.number}次型"
  end

  def edit
    @condition = Condition.find(params[:id])
    @product_mold_lists = {}
    Mold.all.each do |mold|
      @product_mold_lists.store("#{Product.find(mold.product_id).name} #{mold.number}次型", mold.id)
    end
    add_breadcrumb "#{@condition.machine.name}号機 #{@condition.mold.product.name} #{@condition.mold.number}次型", :condition_path
    add_breadcrumb '編集'
  end

  def update
    condition = Condition.find(params[:id])
    condition.update(condition_params)
    redirect_to condition_path, notice: '登録内容が更新されました'
  end

  def destroy
    condition = Condition.find(params[:id])
    condition.destroy
    redirect_to conditions_path, notice: '条件表が削除されました'
  end

  private

  def condition_params
    params.require(:condition).permit(:machine_id, :mold_id, :lis, :lis_u, :lis_l, :his, :his_u, :his_l, :sup, :sup_u, :sup_l, :cp, :cp_u, :cp_l, :bt, :bt_u, :bt_l, :ssp, :ssp_u, :ssp_l, :dev, :dev_u, :dev_l, :fmf, :fmf_u, :fmf_l, :mmf, :mmf_u, :mmf_l)
  end
end

app/views/conditions/edit.html.erb
<% provide(:title, "#{@condition.machine.name}号機 #{@condition.mold.product.name} #{@condition.mold.number}次型 条件表の編集") %>
<%= form_with(model: @condition, local: true, class: "card mb-3") do |f| %>
  <div class="card-body">
    <div class="form-group row">
      <%= f.label "生産ライン", for: "machine_id", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.collection_select :machine_id, Machine.all, :id, :name, {prompt: "選択してください"}, {class: "form-control"} %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "品名・金型", for: "mold_id", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.select :mold_id, @product_mold_lists, {include_blank: '選択してください'}, {class: 'form-control'} %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "低速速度 設定値", for: "lis", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :lis, placeholder: "0.25", id: "lis", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "低速速度 上限値", for: "lis_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :lis_u, placeholder: "0.3", id: "lis_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "低速速度 下限値", for: "lis_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :lis_l, placeholder: "0.2", id: "lis_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "高速速度 設定値", for: "his", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :his, placeholder: "3", id: "his", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "高速速度 上限値", for: "his_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :his_u, placeholder: "3.3", id: "his_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "高速速度 下限値", for: "his_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :his_l, placeholder: "2.7", id: "his_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "高速切替位置 設定値", for: "sup", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :sup, placeholder: "380", id: "sup", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "高速切替位置 上限値", for: "sup_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :sup_u, placeholder: "385", id: "sup_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "高速切替位置 下限値", for: "sup_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :sup_l, placeholder: "375", id: "sup_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "鋳造圧力 設定値", for: "cp", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :cp, placeholder: "40", id: "cp", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "鋳造圧力 上限値", for: "cp_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :cp_u, placeholder: "45", id: "cp_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "鋳造圧力 下限値", for: "cp_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :cp_l, placeholder: "35", id: "cp_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "昇圧時間 設定値", for: "bt", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :bt, placeholder: "500", id: "bt", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "昇圧時間 上限値", for: "bt_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :bt_u, placeholder: "1000", id: "bt_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "昇圧時間 下限値", for: "bt_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :bt_l, placeholder: "0", id: "bt_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "真空開始位置 設定値", for: "ssp", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :ssp, placeholder: "150", id: "ssp", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "真空開始位置 上限値", for: "ssp_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :ssp_u, placeholder: "155", id: "ssp_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "真空開始位置 下限値", for: "ssp_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :ssp_l, placeholder: "145", id: "ssp_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "真空度 設定値", for: "dev", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :dev, placeholder: "100", id: "dev", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "真空度 上限値", for: "dev_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :dev_u, placeholder: "120", id: "dev_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "真空度 下限値", for: "dev_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :dev_l, placeholder: "80", id: "dev_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "固定型冷却流量 設定値", for: "fmf", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :fmf, placeholder: "50", id: "fmf", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "固定型冷却流量 上限値", for: "fmf_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :fmf_u, placeholder: "60", id: "fmf_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "固定型冷却流量 下限値", for: "fmf_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :fmf_l, placeholder: "40", id: "fmf_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "可動型冷却流量 設定値", for: "mmf", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :mmf, placeholder: "50", id: "mmf", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "可動型冷却流量 上限値", for: "mmf_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :mmf_u, placeholder: "60", id: "mmf_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "可動型冷却流量 下限値", for: "mmf_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :mmf_l, placeholder: "40", id: "mmf_l", class: "form-control" %>
      </div>
    </div>
    <div class="d-flex justify-content-end">
      <%= f.submit "更新", class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>

app/views/conditions/index.html.erb
<% provide(:title, "条件表一覧") %>
<div class="d-flex justify-content-end">
  <%= link_to new_condition_path, class: "btn btn-sm btn-outline-secondary mb-3" do %>
    <i class="fas fa-plus"></i>
    条件表の新規登録
  <% end %>
</div>
<%= react_component("Conditions") %>

app/views/conditions/new.html.erb
<% provide(:title, "条件表の新規登録") %>
<%= form_with(model: @condition, local: true, class: "card mb-3") do |f| %>
  <div class="card-body">
    <div class="form-group row">
      <%= f.label "生産ライン", for: "machine_id", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.collection_select :machine_id, Machine.all, :id, :name, {prompt: "選択してください"}, {class: "form-control"} %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "品名・金型", for: "mold_id", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.select :mold_id, @product_mold_lists, {include_blank: '選択してください'}, {class: 'form-control'} %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "低速速度 設定値", for: "lis", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :lis, placeholder: "0.25", id: "lis", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "低速速度 上限値", for: "lis_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :lis_u, placeholder: "0.3", id: "lis_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "低速速度 下限値", for: "lis_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :lis_l, placeholder: "0.2", id: "lis_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "高速速度 設定値", for: "his", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :his, placeholder: "3", id: "his", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "高速速度 上限値", for: "his_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :his_u, placeholder: "3.3", id: "his_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "高速速度 下限値", for: "his_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :his_l, placeholder: "2.7", id: "his_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "高速切替位置 設定値", for: "sup", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :sup, placeholder: "380", id: "sup", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "高速切替位置 上限値", for: "sup_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :sup_u, placeholder: "385", id: "sup_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "高速切替位置 下限値", for: "sup_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :sup_l, placeholder: "375", id: "sup_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "鋳造圧力 設定値", for: "cp", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :cp, placeholder: "40", id: "cp", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "鋳造圧力 上限値", for: "cp_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :cp_u, placeholder: "45", id: "cp_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "鋳造圧力 下限値", for: "cp_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :cp_l, placeholder: "35", id: "cp_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "昇圧時間 設定値", for: "bt", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :bt, placeholder: "500", id: "bt", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "昇圧時間 上限値", for: "bt_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :bt_u, placeholder: "1000", id: "bt_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "昇圧時間 下限値", for: "bt_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :bt_l, placeholder: "0", id: "bt_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "真空開始位置 設定値", for: "ssp", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :ssp, placeholder: "150", id: "ssp", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "真空開始位置 上限値", for: "ssp_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :ssp_u, placeholder: "155", id: "ssp_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "真空開始位置 下限値", for: "ssp_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :ssp_l, placeholder: "145", id: "ssp_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "真空度 設定値", for: "dev", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :dev, placeholder: "100", id: "dev", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "真空度 上限値", for: "dev_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :dev_u, placeholder: "120", id: "dev_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "真空度 下限値", for: "dev_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :dev_l, placeholder: "80", id: "dev_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "固定型冷却流量 設定値", for: "fmf", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :fmf, placeholder: "50", id: "fmf", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "固定型冷却流量 上限値", for: "fmf_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :fmf_u, placeholder: "60", id: "fmf_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "固定型冷却流量 下限値", for: "fmf_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :fmf_l, placeholder: "40", id: "fmf_l", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "可動型冷却流量 設定値", for: "mmf", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :mmf, placeholder: "50", id: "mmf", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "可動型冷却流量 上限値", for: "mmf_u", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :mmf_u, placeholder: "60", id: "mmf_u", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label "可動型冷却流量 下限値", for: "mmf_l", class: "col-4 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :mmf_l, placeholder: "40", id: "mmf_l", class: "form-control" %>
      </div>
    </div>
    <div class="d-flex justify-content-end">
      <%= f.submit "新規登録", class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>

app/views/conditions/show.html.erb
<% provide(:title, "#{@condition.machine.name}号機 #{@condition.mold.product.name} #{@condition.mold.number}次型 条件表") %>
<div class="card mb-3">
  <div class="card-body">
    <div class="row">
      <label class="col-4">生産ライン</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.machine.name %>号機</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">品番</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.mold.product.number %></p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">品名</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.mold.product.name %></p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">金型</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.mold.number %>次型</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">低速速度 設定値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.lis %> m/s</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">低速速度 上限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.lis_u %> m/s</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">低速速度 下限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.lis_l %> m/s</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">高速速度 設定値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.his %> m/s</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">高速速度 上限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.his_u %> m/s</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">高速速度 下限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.his_l %> m/s</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">高速切替位置 設定値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.sup %> mm</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">高速切替位置 上限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.sup_u %> mm</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">高速切替位置 下限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.sup_l %> mm</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">鋳造圧力 設定値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.cp %> MPa</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">鋳造圧力 上限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.cp_u %> MPa</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">鋳造圧力 下限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.cp_l %> MPa</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">昇圧時間 設定値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.bt %> ms</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">昇圧時間 上限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.bt_u %> ms</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">昇圧時間 下限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.bt_l %> ms</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">真空開始位置 設定値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.ssp %> mm</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">真空開始位置 上限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.ssp_u %> mm</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">真空開始位置 下限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.ssp_l %> mm</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">真空度 設定値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.dev %> torr</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">真空度 上限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.dev_u %> torr</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">真空度 下限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.dev_l %> torr</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">固定型冷却流量 設定値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.fmf %> ml</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">固定型冷却流量 上限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.fmf_u %> ml</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">固定型冷却流量 下限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.fmf_l %> ml</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">可動型冷却流量 設定値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.mmf %> ml</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">可動型冷却流量 上限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.mmf_u %> ml</p>
      </div>
    </div>
    <div class="row">
      <label class="col-4">可動型冷却流量 下限値</label>
      <div class="col-8">
        <p class="card-text"><%= @condition.mmf_l %> ml</p>
      </div>
    </div>
    <div class="d-flex justify-content-end">
      <%= link_to edit_condition_path, class: "btn btn-outline-secondary" do %>
        <i class="fas fa-edit"></i>
        編集
      <% end %>
      <%= link_to condition_path(@condition), method: :delete, class: "btn btn-outline-danger ml-2" do %>
        <i class="fas fa-trash-alt"></i>
        削除
      <% end %>
    </div>
  </div>
</div>