config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'logs#index'

  resources :logs, only: %i[index show]

  resources :conditions do
    collection do
      get 'search'
    end
  end

  resources :products do
    resources :molds, only: %i[new create show destroy]
  end

  resources :machines
end

app/models/machine.rb
# frozen_string_literal: true

# Machine class
class Machine < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :conditions
  has_many :logs
end

app/controllers/machines_controller.rb
# frozen_string_literal: true

# Machines controller
class MachinesController < ApplicationController
  add_breadcrumb '生産ライン一覧', :machines_path

  def index
    @machines = Machine.all
  end

  def new
    @machine = Machine.new
    add_breadcrumb '新規登録'
  end

  def create
    Machine.create(machine_params)
    redirect_to machines_path, notice: '新しい生産ラインが登録されました'
  end

  def show
    @machine = Machine.find(params[:id])
    add_breadcrumb "#{@machine.name}号機"
  end

  def edit
    @machine = Machine.find(params[:id])
    add_breadcrumb "#{@machine.name}号機", :machine_path
    add_breadcrumb '編集'
  end

  def update
    machine = Machine.find(params[:id])
    machine.update(machine_params)
    redirect_to machine_path, notice: '登録内容が更新されました'
  end

  def destroy
    machine = Machine.find(params[:id])
    machine.destroy
    redirect_to machines_path, notice: '生産ラインが削除されました'
  end

  private

  def machine_params
    params.require(:machine).permit(:name)
  end
end

app/views/machines/edit.html.erb
<% provide(:title, "#{@machine.name}号機の編集") %>
<%= form_with(model: @machine, local: true, class: "card mb-3") do |f| %>
  <div class="card-body">
    <div class="form-group">
      <%= f.label "生産ライン", for: "machine"%>
      <%= f.text_field :name, placeholder: "1-1", id: "machine", class: "form-control" %>
    </div>
    <div class="d-flex justify-content-end">
      <%= f.submit "更新", class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>

app/views/machines/index.html.erb
<% provide(:title, "生産ライン一覧") %>
<div class="d-flex justify-content-end">
  <%= link_to new_machine_path, class: "btn btn-sm btn-outline-secondary mb-3" do %>
    <i class="fas fa-plus"></i>
    生産ラインの新規登録
  <% end %>
</div>
<div class="list-group mb-3">
  <% @machines.each do |machine| %>
    <%= link_to "#{machine.name}号機", machine_path(machine), class: "list-group-item list-group-item-action" %>
  <% end %>
</div>

app/views/machines/new.html.erb
<% provide(:title, "生産ラインの新規登録") %>
<%= form_with(model: @machine, local: true, class: "card mb-3") do |f| %>
  <div class="card-body">
    <div class="form-group">
      <%= f.label "生産ライン", for: "machine"%>
      <%= f.text_field :name, placeholder: "1-1", id: "machine", class: "form-control" %>
    </div>
    <div class="d-flex justify-content-end">
      <%= f.submit "新規登録", class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>

app/views/machines/show.html.erb
<% provide(:title, "#{@machine.name}号機") %>
<div class="card mb-3">
  <div class="card-body">
    <p class="card-text">生産ライン：<%= @machine.name %>号機</p>
    <div class="d-flex justify-content-end">
      <%= link_to edit_machine_path, class: "btn btn-outline-secondary" do %>
        <i class="fas fa-edit"></i>
        編集
      <% end %>
      <%= link_to machine_path(@machine), method: :delete, class: "btn btn-outline-danger ml-2" do %>
        <i class="fas fa-trash-alt"></i>
        削除
      <% end %>
    </div>
  </div>
</div>