config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'logs#index'

  resources :logs, only: %i[index show]

  resources :conditions do
    collection do
      get 'search'
    end
  end

  resources :products do
    resources :molds, only: %i[new create show destroy]
  end

  resources :machines
end

app/models/product.rb
# frozen_string_literal: true

# Product class
class Product < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  has_many :molds
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Products controller class
class ProductsController < ApplicationController
  add_breadcrumb '品種一覧', :products_path

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    add_breadcrumb '新規登録'
  end

  def create
    Product.create(product_params)
    redirect_to products_path, notice: '新しい品種が登録されました'
  end

  def show
    @product = Product.find(params[:id])
    add_breadcrumb @product.name
  end

  def edit
    @product = Product.find(params[:id])
    add_breadcrumb @product.name, :product_path
    add_breadcrumb '編集'
  end

  def update
    product = Product.find(params[:id])
    product.update(product_params)
    redirect_to product_path, notice: '登録内容が更新されました'
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_path, notice: '生産ラインが削除されました'
  end

  private

  def product_params
    params.require(:product).permit(:number, :name)
  end
end

app/views/products/edit.html.erb
<% provide(:title, "#{@product.name}の編集") %>
<%= form_with(model: @product, local: true, class: "card mb-3") do |f| %>
  <div class="card-body">
    <div class="form-group">
      <%= f.label "品番", for: "number"%>
      <%= f.text_field :number, placeholder: "000000-00000", id: "number", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "品名", for: "name"%>
      <%= f.text_field :name, placeholder: "00000", id: "name", class: "form-control" %>
    </div>
    <div class="d-flex justify-content-end">
      <%= f.submit "更新", class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>

app/views/products/index.html.erb
<% provide(:title, "品種一覧") %>
<div class="d-flex justify-content-end">
  <%= link_to new_product_path, class: "btn btn-sm btn-outline-secondary mb-3" do %>
    <i class="fas fa-plus"></i>
    品種の新規登録
  <% end %>
</div>
<div class="list-group mb-3">
  <% @products.each do |product| %>
    <%= link_to product.name, product_path(product), class: "list-group-item list-group-item-action" %>
  <% end %>
</div>

app/views/products/new.html.erb
<% provide(:title, "品種の新規登録") %>
<%= form_with(model: @product, local: true, class: "card mb-3") do |f| %>
  <div class="card-body">
    <div class="form-group">
      <%= f.label "品番", for: "number"%>
      <%= f.text_field :number, placeholder: "000000-00000", id: "number", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "品名", for: "name"%>
      <%= f.text_field :name, placeholder: "00000", id: "name", class: "form-control" %>
    </div>
    <div class="d-flex justify-content-end">
      <%= f.submit "新規登録", class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>
<div class="card mb-3">
  <div class="card-body">
    <p class="card-text">品番：<%= @product.number %></p>
    <p class="card-text">品名：<%= @product.name %></p>
    <p class="card-text">金型：
      <% @product.molds.each_with_index do |mold, i| %>
        <% unless i == @product.molds.length - 1 %>
          <%= link_to mold.number, product_mold_path(@product, mold) %>, 
        <% else %>
          <%= link_to mold.number, product_mold_path(@product, mold) %>次型
        <% end %>
      <% end %>
      <%= link_to new_product_mold_path(@product), class: "badge badge-secondary ml-2" do %>
        <i class="fas fa-plus"></i>
        金型の新規登録
      <% end %>
    </p>
    <div class="d-flex justify-content-end">
      <%= link_to edit_product_path, class: "btn btn-outline-secondary" do %>
        <i class="fas fa-edit"></i>
        編集
      <% end %>
      <%= link_to product_path(@product), method: :delete, class: "btn btn-outline-danger ml-2" do %>
        <i class="fas fa-trash-alt"></i>
        削除
      <% end %>
    </div>
  </div>
</div>