config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'logs#index'

  resources :logs, only: %i[index show]

  resources :conditions do
    collection do
      get 'search'
    end
  end

  resources :products do
    resources :molds, only: %i[new create show destroy]
  end

  resources :machines
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark shadow">
      <%= link_to "条件管理モニター", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto d-md-none">
          <li class="nav-item <%= "active" if controller.controller_name == "logs" %>">
            <%= link_to "ロギングデータ", logs_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= "active" if controller.controller_name == "conditions" %>">
            <%= link_to "条件表", conditions_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= "active" if controller.controller_name == "products" %>">
            <%= link_to "品種", products_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= "active" if controller.controller_name == "machines" %>">
            <%= link_to "生産ライン", machines_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row vh-100 pt-56px">
        <div class="d-none d-md-block w-25 bg-light border-right">
          <aside class="list-group list-group-flush">
            <%= link_to "ロギングデータ", logs_path, class: "list-group-item list-group-item-action bg-light font-weight-bold #{"text-primary" if controller.controller_name == "logs"}" %>
            <%= link_to "条件表", conditions_path, class: "list-group-item list-group-item-action bg-light font-weight-bold #{"text-primary" if controller.controller_name == "conditions"}" %>
            <%= link_to "品種", products_path, class: "list-group-item list-group-item-action bg-light font-weight-bold #{"text-primary" if controller.controller_name == "products"}" %>
            <%= link_to "生産ライン", machines_path, class: "list-group-item list-group-item-action bg-light font-weight-bold #{"text-primary" if controller.controller_name == "machines"}" %>
          </aside>
        </div>
        <div class="col-sm-12 col-md-9 h-100 overflow-auto">
          <main class="mb-4">
            <h1 class="h2 pt-3 pb-2 mb-3 border-bottom"><%= yield(:title) %></h1>
            <div class="px-3 py-1 mb-3 bg-light border rounded-pill">
              <%= render_breadcrumbs separator: " / " %>
            </div>
            <% if notice %>
              <div class="alert alert-success alert-dismissible fade show mb-3" role="alert">
                <%= notice %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            <% end %>
            <%= yield %>
          </main>
          <footer class="row justify-content-center align-items-center bg-secondary">
            <%= link_to "https://github.com/higemegane1992/cmm", class: "text-white py-3", target: :_blank do %>
              <i class="fab fa-github"></i>
              Github
            <% end %>
          </footer>
        </div>
      </div>
    </div>
  </body>
</html>